name = "BeamPaths"
uuid = "8a37c4aa-b076-42cf-b9ad-9c2f59f0ee2f"
authors = ["Michael Lackner"]
version = "0.1.0"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
